### ISSUE TITLE
Animated Ring not showing up

### ISSUE THREAD

**Issue by FearedFusionX** [p0rtL6/BD-AnimatedSpeakingRings#7]
The Ring when you talk doesn't show up what-so-ever. Can you fix this?

Screenshot below.

![Screenshot 2023-09-09 153933346534](https://github.com/p0rtL6/BD-AnimatedSpeakingRings/assets/88568205/09759163-eb46-4238-9789-b30086e4d356)
![Screenshot 2023-09-09 153933](https://github.com/p0rtL6/BD-AnimatedSpeakingRings/assets/88568205/1b44b53b-a66f-42ac-9c52-fae35ee9544d)

**Comment by p0rtL6** [comment]
Sorry this plugin is not maintained anymore, I will mark the repository accordingly, feel free to submit any pull requests with fixes or updates and I will take a look at them.
